ORCA2/Controllers/ExpertisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ORCA2.Models;

namespace ORCA2.Controllers
{
    public class ExpertisesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Expertises
        public ActionResult Index(string department, string searchString)
        {
            var DepLst = new List<string>();

            var GenreQry = from d in db.Expertises
                           orderby d.Department
                           select d.Department;

            DepLst.AddRange(GenreQry.Distinct());
            ViewBag.department = new SelectList(DepLst);

            var expertiseList = from m in db.Expertises
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                expertiseList = expertiseList.Where(s => s.Field.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(department))
            {
                expertiseList = expertiseList.Where(x => x.Department == department);
            }

            return View(expertiseList);
        }

        // GET: Expertises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expertise expertise = db.Expertises.Find(id);
            if (expertise == null)
            {
                return HttpNotFound();
            }
            return View(expertise);
        }

        // GET: Expertises/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Expertises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExpertiseID,ContactEmail,Department,Field,Validated")] Expertise expertise)
        {
            if (ModelState.IsValid)
            {
                expertise.LinkedEmail = User.Identity.Name;
                expertise.Validated = false;
                db.Expertises.Add(expertise);
                db.SaveChanges();
                return RedirectToAction("Index", "Manage");
            }

            return View(expertise);
        }

        // GET: Expertises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expertise expertise = db.Expertises.Find(id);
            if (expertise == null)
            {
                return HttpNotFound();
            }
            return View(expertise);
        }

        // POST: Expertises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpertiseID, Field, Department, LinkedEmail, ContactEmail, Validated")] Expertise expertise)
        {
            if (ModelState.IsValid)
            {
                //expertise.Validated = true;
                db.Entry(expertise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expertise);
        }

        // GET: Expertises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expertise expertise = db.Expertises.Find(id);
            if (expertise == null)
            {
                return HttpNotFound();
            }
            return View(expertise);
        }

        // POST: Expertises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expertise expertise = db.Expertises.Find(id);
            db.Expertises.Remove(expertise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ORCA2/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ORCA2.Models;

namespace ORCA2.Controllers
{
    public class MessagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Messages
        public ActionResult Index()
        {
            return View(db.Messages.ToList());
        }

        // GET: Messages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // GET: Messages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MessageID,User1ID,User2ID,Title,InitialMessage")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(message);
        }

        // GET: Messages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MessageID,User1ID,User2ID,Title,InitialMessage")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ORCA2/Controllers/RepliesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ORCA2.Models;

namespace ORCA2.Controllers
{
    public class RepliesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Replies
        public ActionResult Index()
        {
            return View(db.Replies.ToList());
        }

        // GET: Replies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.Replies.Find(id);
            if (reply == null)
            {
                return HttpNotFound();
            }
            return View(reply);
        }

        // GET: Replies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Replies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReplyID,MessageID,ID,Content,Timestamp")] Reply reply)
        {
            if (ModelState.IsValid)
            {
                db.Replies.Add(reply);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reply);
        }

        // GET: Replies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.Replies.Find(id);
            if (reply == null)
            {
                return HttpNotFound();
            }
            return View(reply);
        }

        // POST: Replies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReplyID,MessageID,ID,Content,Timestamp")] Reply reply)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reply).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reply);
        }

        // GET: Replies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reply reply = db.Replies.Find(id);
            if (reply == null)
            {
                return HttpNotFound();
            }
            return View(reply);
        }

        // POST: Replies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reply reply = db.Replies.Find(id);
            db.Replies.Remove(reply);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ORCA2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ORCA Consulting</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <style>
        .navbar-inverse {
            background-color: lightgray;
            position: relative; 
        }
        .navbar-default {
            background-color: green;
        }
    </style>
    <!---<nav class="nav navbar-default navbar-fixed-top" style="background-color: black;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="Home/Index" style="color: white; font-size: large;">Welcome To The Online Report And Consulting Application</a>
            </div>
        </div>
    </nav>-->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="Home/Index" style="color:white; font-size: large; font-weight: bold;">Welcome To The Online Reporting and Consulting Application</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="https://mymu.marshall.edu/" style="color: white;"><span class="glyphicon glyphicon-user"></span>MyMU</a></li>
                <li><a href="https://www.marshall.edu/muonline/" style="color: white;"><span class="glyphicon glyphicon-user"></span>MuOnline</a></li>
                <li><a href="http://www.marshall.edu/phonebook.php" style="color: white;"><span class="glyphicon glyphicon-book"></span>Directory</a></li>
            </ul>
        </div>
        <style>
            .navbar-right li a span {
                color: white;
                font-size: medium;
            }
        </style>
    </nav>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <img src="http://www.marshall.edu/home/img/main/mu_logo_blk.png" />
            <style>
                img {
                    width: 250px;
                    height: 65px;
                    margin-right: 3em;
                }
            </style>
            <div class="navbar-header">
                <!----<a class="navbar-brand" href="Home/Index">ORCA Consulting</a>-->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About ORCA", "About", "Home")</li>
                    <li>@Html.ActionLink("Expert Contact Information", "Contact", "Home")</li>
                    <!--<li><a href="Home/Index" style="color: black;">Home</a></li>
                    <li><a href="Home/About" style="color: black;">About ORCA</a></li>
                    <li><a href="Home/Contact" style="color: black;">Expert Contact Information</a></li>-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="UserLists/Index" style="color: black;">Users
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Send Message To Expert", "Create", "Messages")</li>
                            <li>@Html.ActionLink("List Of All Messages", "Index", "Messages") </li>
                            <li>@Html.ActionLink("List Of All Validated Experts", "Index", "Expertises")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="Experts/Index" style="color: black;">Experts
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Reply To An Expert", "Create", "Replies")</li>
                            <li>@Html.ActionLink("List Of All Validated Experts", "Index", "Expertises")</li>
                            <!--<li><a href="Replies/Create">Reply To An Expert</a></li>
                            <li><a href="Experts/Index">List Of All Validated Experts</a></li>-->
                        </ul>
                    </li>
                </ul>
                <style>
                    ul li a {
                        font-size: medium;
                        font-weight: bold;
                    }
                </style>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <span class="glyphicon glyphicon-search"></span>
                        <input type="text" class="form-control" placeholder="Search By Expertise" href="Expertise/Index"style="width: 200px;"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
               <p>&copy; @DateTime.Now.Year - ORCA Consulting</p>
            </footer>
        </div> 


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>